
export const roomsData = [
    {
      "id": 1,
      "name": 'Pokój 2-osobowy z łazienką',
      "rodzaj": 'dwojka',
      "klimatyzacja": true,
      "lazienka": true,
      "balkon": false,
      "aneks_kuchenny": false,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": true,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
     {
      "id": 2,
      "name": 'Pokój 2-osobowy z "balkon"em',
      "rodzaj": 'dwojka',
      "klimatyzacja": false,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": false,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
     {
      "id": 3,
      "name": 'Pokój 3-osobowy z "balkon"em',
      "rodzaj": 'trojka',
      "klimatyzacja": true,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": false,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
     {
      "id": 4,
      "name": 'Pokój 4-osobowy z "balkon"em',
      "rodzaj": 'czworka',
      "klimatyzacja": true,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": true,
      "parter": false,
      "alergia": true,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": true,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
     {
      "id": 5,
      "name": 'Pokój 3-osobowy z "balkon"em',
      "rodzaj": 'trojka',
      "klimatyzacja": true,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": true,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": false,
      "sniadanie": true,
      "budzenie": true
     },
     {
      "id": 6,
      "name": 'Mały pokój 2-osobowy',
      "rodzaj": 'dwojka',
      "klimatyzacja": false,
      "lazienka": true,
      "balkon": false,
      "aneks_kuchenny": false,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
     {
      "id": 7,
      "name": 'Pokój 3-osobowy z "balkon"em',
      "rodzaj": 'trojka',
      "klimatyzacja": false,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": false,
      "parter": false,
      "alergia": false,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": true,
      "sniadanie": true,
      "budzenie": false
     },
    {
      "id": 8,
      "name": 'Pokój 4-osobowy z "balkon"em',
      "rodzaj": 'czworka',
      "klimatyzacja": true,
      "lazienka": true,
      "balkon": true,
      "aneks_kuchenny": true,
      "parter": false,
      "alergia": true,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": false,
      "parking": false,
      "sniadanie": true,
      "budzenie": true
     },
    {
      "id": 9,
      "name": 'Pokój 4-osobowy',
      "rodzaj": 'czworka',
      "klimatyzacja": false,
      "lazienka": true,
      "balkon": false,
      "aneks_kuchenny": false,
      "parter": true,
      "alergia": true,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": true,
      "parking": false,
      "sniadanie": true,
      "budzenie": false
     },
    {
      "id": 10,
      "name": 'Pokój 2-osobowy',
      "rodzaj": 'dwojka',
      "klimatyzacja": false,
      "lazienka": true,
      "balkon": false,
      "aneks_kuchenny": false,
      "parter": true,
      "alergia": true,
      "zameldowanie": true,
      "zwierze": true,
      "dostawka": true,
      "parking": true,
      "sniadanie": true,
      "budzenie": false
     },
  ];